---
- name: install nginx server on ubuntu and RedHat
  hosts: website
  become: yes
  tasks:
    - name: install nginx server on ubuntu
      ansible.builtin.apt:
         name: nginx
         update_cache: yes
         state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: ensure nginx service is running 
      ansible.builtin.systemd_service:
        name: nginx
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "Debian"
    - name: install nginx server on RedHat
      ansible.builtin.dnf:
         name: nginx
         update_cache: yes
         state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: ensure nginx service is running 
      ansible.builtin.systemd_service:
        name: nginx
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "RedHat"
